# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b2dbccaef5519cf47c6ef2e1394986537e7a179549a880932781e269d43ddb4f5b40f646f9ed747fe6440e19a225d8b941f2cfe8b8814d7fe82e631e574f8a2

test:
  secret_key_base: 9030a79d4eb9fbc4f16c8cc216d7054cc514d414effb24dc45fcaf70b475dc267be10b1a09247f670efa5e39818f46aa45594f16d812ce0de26558fe506653dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
