# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de947e657054bd8ee5f4016569e52fa40fc92a1eac1699dfaeda827c5e2d44d4c52f13e8c03fff258c0b245c35ec6566b5e9a679d852bd943b951fc5f008490f

test:
  secret_key_base: f99c7135da67dc2e5caac05e82a0a0e2347f6e3f808ad1615b854954c846fad93dcf4f5acac13c9c891eac82fe9314a74329c2e92f3411d6647f38b17b268eaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
