# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 153e586eca337393188140cb0aa20fb9b8bac847305eb9b74060ea035d9e013eb08a1a3b3e6099e7621a461d0e4bca045b41ce785b75888cffdc634d81058621

test:
  secret_key_base: 49f12ac66a0f142136f10f38cc1d695a7de8a1129789ca4078bb65fe60fcd22afb95125afc25200681dc8f1486a77c0dcee5097cbbe29b7246214e3c4b30464e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
